//------------------------------------------------------------------------------
// <auto-generated>
//     Tento kód byl generován nástrojem.
//     Verze modulu runtime:4.0.30319.42000
//
//     Změny tohoto souboru mohou způsobit nesprávné chování a budou ztraceny,
//     dojde-li k novému generování kódu.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JobSniper.Properties {
    using System;
    
    
    /// <summary>
    ///   Třída prostředků se silnými typy pro vyhledávání lokalizovaných řetězců atp.
    /// </summary>
    // Tato třída byla automaticky generována třídou StronglyTypedResourceBuilder
    // pomocí nástroje podobného aplikaci ResGen nebo Visual Studio.
    // Chcete-li přidat nebo odebrat člena, upravte souboru .ResX a pak znovu spusťte aplikaci ResGen
    // s parametrem /str nebo znovu sestavte projekt aplikace Visual Studio.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Vrací instanci ResourceManager uloženou v mezipaměti použitou touto třídou.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("JobSniper.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Potlačí vlastnost CurrentUICulture aktuálního vlákna pro všechna
        ///   vyhledání prostředků pomocí třídy prostředků se silnými typy.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný 🎯 JobSniper.
        /// </summary>
        public static string AppTitle {
            get {
                return ResourceManager.GetString("AppTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný ❌ Delete.
        /// </summary>
        public static string Btn_Delete {
            get {
                return ResourceManager.GetString("Btn_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný ✏️ Edit.
        /// </summary>
        public static string Btn_Edit {
            get {
                return ResourceManager.GetString("Btn_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný ♻️ Unblock.
        /// </summary>
        public static string Btn_Unblock {
            get {
                return ResourceManager.GetString("Btn_Unblock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný 🌐 Web.
        /// </summary>
        public static string Btn_Web {
            get {
                return ResourceManager.GetString("Btn_Web", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný ➕ Add new company manually.
        /// </summary>
        public static string Crm_BtnAddCompany {
            get {
                return ResourceManager.GetString("Crm_BtnAddCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný New Company.
        /// </summary>
        public static string Crm_NewCompany {
            get {
                return ResourceManager.GetString("Crm_NewCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný 🏢 CRM - Company Database.
        /// </summary>
        public static string Crm_Title {
            get {
                return ResourceManager.GetString("Crm_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Company Aliases (comma separated):.
        /// </summary>
        public static string CrmWindow_AliasesLabel {
            get {
                return ResourceManager.GetString("CrmWindow_AliasesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný If the company operates under multiple names, list them here..
        /// </summary>
        public static string CrmWindow_AliasesTooltip {
            get {
                return ResourceManager.GetString("CrmWindow_AliasesTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Cancel.
        /// </summary>
        public static string CrmWindow_BtnCancel {
            get {
                return ResourceManager.GetString("CrmWindow_BtnCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný 💾 Save to CRM.
        /// </summary>
        public static string CrmWindow_BtnSave {
            get {
                return ResourceManager.GetString("CrmWindow_BtnSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný ⛔ Company is blocked (auto-trash).
        /// </summary>
        public static string CrmWindow_ChkBlocked {
            get {
                return ResourceManager.GetString("CrmWindow_ChkBlocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Company Name.
        /// </summary>
        public static string CrmWindow_CompanyName {
            get {
                return ResourceManager.GetString("CrmWindow_CompanyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Interaction history and notes:.
        /// </summary>
        public static string CrmWindow_HistoryLabel {
            get {
                return ResourceManager.GetString("CrmWindow_HistoryLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Blue (History exists).
        /// </summary>
        public static string CrmWindow_RepInfo {
            get {
                return ResourceManager.GetString("CrmWindow_RepInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný No color (Unknown).
        /// </summary>
        public static string CrmWindow_RepNeutral {
            get {
                return ResourceManager.GetString("CrmWindow_RepNeutral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Reputation (Inbox Highlights):.
        /// </summary>
        public static string CrmWindow_ReputationLabel {
            get {
                return ResourceManager.GetString("CrmWindow_ReputationLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Orange (Issue/Warning).
        /// </summary>
        public static string CrmWindow_RepWarning {
            get {
                return ResourceManager.GetString("CrmWindow_RepWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný CRM Company Detail.
        /// </summary>
        public static string CrmWindow_Title {
            get {
                return ResourceManager.GetString("CrmWindow_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Background processes (Scraper).
        /// </summary>
        public static string Dashboard_BackgroundProcesses {
            get {
                return ResourceManager.GetString("Dashboard_BackgroundProcesses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný My Opportunities.
        /// </summary>
        public static string Dashboard_MyOpportunities {
            get {
                return ResourceManager.GetString("Dashboard_MyOpportunities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Dashboard / Overview.
        /// </summary>
        public static string Dashboard_Title {
            get {
                return ResourceManager.GetString("Dashboard_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Trashed: Auto / Manual.
        /// </summary>
        public static string Dashboard_Trashed {
            get {
                return ResourceManager.GetString("Dashboard_Trashed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Waiting in Inbox.
        /// </summary>
        public static string Dashboard_WaitingInbox {
            get {
                return ResourceManager.GetString("Dashboard_WaitingInbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Actions.
        /// </summary>
        public static string Grid_Actions {
            get {
                return ResourceManager.GetString("Grid_Actions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Company.
        /// </summary>
        public static string Grid_Company {
            get {
                return ResourceManager.GetString("Grid_Company", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Company Name.
        /// </summary>
        public static string Grid_CompanyName {
            get {
                return ResourceManager.GetString("Grid_CompanyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Last Contact.
        /// </summary>
        public static string Grid_LastContact {
            get {
                return ResourceManager.GetString("Grid_LastContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Location.
        /// </summary>
        public static string Grid_Location {
            get {
                return ResourceManager.GetString("Grid_Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Position.
        /// </summary>
        public static string Grid_Position {
            get {
                return ResourceManager.GetString("Grid_Position", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Reputation.
        /// </summary>
        public static string Grid_Reputation {
            get {
                return ResourceManager.GetString("Grid_Reputation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Salary.
        /// </summary>
        public static string Grid_Salary {
            get {
                return ResourceManager.GetString("Grid_Salary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Seen.
        /// </summary>
        public static string Grid_Seen {
            get {
                return ResourceManager.GetString("Grid_Seen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný 🗄️ Archive ({0}).
        /// </summary>
        public static string Menu_Archive_Format {
            get {
                return ResourceManager.GetString("Menu_Archive_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný 🏢 CRM (Companies).
        /// </summary>
        public static string Menu_Crm {
            get {
                return ResourceManager.GetString("Menu_Crm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný 📊 Dashboard.
        /// </summary>
        public static string Menu_Dashboard {
            get {
                return ResourceManager.GetString("Menu_Dashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný 🔁 Session Duplicates ({0}).
        /// </summary>
        public static string Menu_Duplicates_Format {
            get {
                return ResourceManager.GetString("Menu_Duplicates_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný 📥 Inbox ({0}).
        /// </summary>
        public static string Menu_Inbox_Format {
            get {
                return ResourceManager.GetString("Menu_Inbox_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný ⭐ Opportunities ({0}).
        /// </summary>
        public static string Menu_Opportunities_Format {
            get {
                return ResourceManager.GetString("Menu_Opportunities_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný ⚙️ Settings &amp; Filters.
        /// </summary>
        public static string Menu_Settings {
            get {
                return ResourceManager.GetString("Menu_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný 🗑️ Trash ({0}).
        /// </summary>
        public static string Menu_Trash_Format {
            get {
                return ResourceManager.GetString("Menu_Trash_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Add new URL to scrape:.
        /// </summary>
        public static string Settings_AddUrlLabel {
            get {
                return ResourceManager.GetString("Settings_AddUrlLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Add URL.
        /// </summary>
        public static string Settings_BtnAddUrl {
            get {
                return ResourceManager.GetString("Settings_BtnAddUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný This company is blacklisted (Automatically trashed).
        /// </summary>
        public static string Tooltip_Blacklisted {
            get {
                return ResourceManager.GetString("Tooltip_Blacklisted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Block company.
        /// </summary>
        public static string Tooltip_Block {
            get {
                return ResourceManager.GetString("Tooltip_Block", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Add/View CRM note.
        /// </summary>
        public static string Tooltip_Crm {
            get {
                return ResourceManager.GetString("Tooltip_Crm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný This company has history in CRM.
        /// </summary>
        public static string Tooltip_CrmHistory {
            get {
                return ResourceManager.GetString("Tooltip_CrmHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný CRM Warning (Caution).
        /// </summary>
        public static string Tooltip_CrmWarning {
            get {
                return ResourceManager.GetString("Tooltip_CrmWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Move to opportunities.
        /// </summary>
        public static string Tooltip_Opportunity {
            get {
                return ResourceManager.GetString("Tooltip_Opportunity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Move to trash.
        /// </summary>
        public static string Tooltip_Trash {
            get {
                return ResourceManager.GetString("Tooltip_Trash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Unblock company and restore offers.
        /// </summary>
        public static string Tooltip_Unblock {
            get {
                return ResourceManager.GetString("Tooltip_Unblock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný JobSniper - My career zen.
        /// </summary>
        public static string WindowTitle {
            get {
                return ResourceManager.GetString("WindowTitle", resourceCulture);
            }
        }
    }
}
