<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="..\JobSniper\CompanyProfile.cs" Link="Models\CompanyProfile.cs" />
    <Compile Include="..\JobSniper\JobOffer.cs" Link="Models\JobOffer.cs" />
  </ItemGroup>

</Project>
